[package]
name = "rsa"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.9.0"
uint = "0.8"
num-primes = "0.3.0"   
num-bigint = "0.2.6"  
num-integer = "0.1.46"
modinverse = "0.1.1"
num-traits = "0.2"